### ISSUE TITLE
[BUG] Crash when use mouse wheel wheeling book to thaumic tinkerer's osmotic enchanter

### ISSUE THREAD

**Issue by KELETU66666** [CleanroomMC/MouseTweaks#7]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-03-05 23:28:04 CST
Description: handleMouseClick() threw an exception when called from MouseTweaks.

java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at yalter.mousetweaks.handlers.GuiContainerHandler.clickSlot(GuiContainerHandler.java:102)
    at yalter.mousetweaks.Main.handleWheel(Main.java:278)
    at yalter.mousetweaks.Main.onUpdateInGui(Main.java:201)
    at yalter.mousetweaks.Main.onUpdateInGame(Main.java:58)
    at yalter.mousetweaks.MouseTweaks.onRenderTick(MouseTweaks.java:83)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1211_MouseTweaks_onRenderTick_RenderTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1117)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
    at oolloo.jlw.Wrapper.main(Wrapper.java:51)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
    at java.util.Arrays$ArrayList.set(Unknown Source)
    at net.minecraft.util.NonNullList.set(SourceFile:51)
    at net.minecraft.inventory.InventoryBasic.setInventorySlotContents(SourceFile:100)
    at net.minecraft.inventory.Slot.putStack(Slot.java:70)
    at net.minecraft.inventory.Container.slotClick(Container.java:281)
    at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:566)
    at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:638)
    ... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Transmit_fault'/3, l='MpServer', x=600.46, y=102.75, z=232.09]]
  Chunk stats: MultiplayerChunkCache: 169, 169
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (196,64,256), Chunk: (at 4,4,0 in 12,16; contains blocks 192,0,256 to 207,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 2385116 game time, 3096490 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 28 total; [EntityCelestialObserver['天象瞭望镜'/1, l='MpServer', x=600.48, y=95.88, z=261.52], EntitySnowman['雪傀儡'/2, l='MpServer', x=616.65, y=95.00, z=259.35], EntityCreeper['爬行者'/4, l='MpServer', x=521.49, y=30.00, z=185.19], EntitySkeleton['骷髅'/6, l='MpServer', x=527.50, y=28.00, z=187.50], EntityZombie['僵尸'/71, l='MpServer', x=674.50, y=35.00, z=204.50], EntityPlayerSP['Transmit_fault'/3, l='MpServer', x=600.46, y=102.75, z=232.09], EntitySheep['羊'/72, l='MpServer', x=647.78, y=93.00, z=225.33], EntityChicken['鸡'/73, l='MpServer', x=585.81, y=94.00, z=292.50], EntityZombie['僵尸'/8395, l='MpServer', x=543.50, y=78.00, z=154.21], EntityZombie['僵尸'/8396, l='MpServer', x=542.50, y=79.00, z=153.50], EntityZombie['僵尸'/13, l='MpServer', x=522.50, y=35.00, z=309.50], EntitySkeleton['骷髅'/8404, l='MpServer', x=551.50, y=97.00, z=152.50], EntityBat['蝙蝠'/8405, l='MpServer', x=575.43, y=41.71, z=159.78], EntityBat['蝙蝠'/918, l='MpServer', x=549.43, y=17.24, z=171.76], EntityCreeper['爬行者'/8408, l='MpServer', x=585.50, y=95.00, z=152.50], EntityBat['蝙蝠'/28, l='MpServer', x=674.71, y=35.22, z=274.15], EntitySkeleton['骷髅'/8413, l='MpServer', x=655.50, y=94.00, z=159.50], EntitySheep['羊'/94, l='MpServer', x=647.18, y=95.00, z=255.73], EntityZombie['僵尸'/8415, l='MpServer', x=664.50, y=24.00, z=155.50], EntityZombie['僵尸'/8416, l='MpServer', x=664.50, y=24.00, z=154.50], EntityCreeper['爬行者'/8417, l='MpServer', x=665.50, y=24.00, z=153.50], EntityBat['蝙蝠'/1002, l='MpServer', x=588.89, y=30.76, z=310.18], EntitySheep['羊'/106, l='MpServer', x=530.76, y=94.00, z=240.54], EntityBat['蝙蝠'/874, l='MpServer', x=559.64, y=21.77, z=177.71], EntitySkeleton['骷髅'/57, l='MpServer', x=672.50, y=34.00, z=176.50], EntityZombie['僵尸'/59, l='MpServer', x=675.50, y=33.00, z=177.50], EntityCreeper['爬行者'/126, l='MpServer', x=655.50, y=27.00, z=162.50], EntityCreeper['爬行者'/127, l='MpServer', x=652.50, y=27.00, z=165.50]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_331, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1189654056 bytes (1134 MB) / 2583691264 bytes (2464 MB) up to 3221225472 bytes (3072 MB)
  JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx3072m
  IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2859 99 mods loaded, 99 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                        | Version               | Source                                        | Signature                                |
       |:------ |:------------------------- |:--------------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                 | 1.12.2                | minecraft.jar                                 | None                                     |
       | LCHIJA | mcp                       | 9.42                  | minecraft.jar                                 | None                                     |
       | LCHIJA | bansoukou                 | 4.3.1                 | minecraft.jar                                 | None                                     |
       | LCHIJA | FML                       | 8.0.99.99             | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                     | 14.23.5.2859          | forge-1.12.2-14.23.5.2859.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | smoothfontcore            | mc1.12.2-2.1.4        | minecraft.jar                                 | None                                     |
       | LCHIJA | xaerominimap_core         | 1.12.2-1.0            | minecraft.jar                                 | None                                     |
       | LCHIJA | xaeroworldmap_core        | 1.12.2-1.0            | minecraft.jar                                 | None                                     |
       | LCHIJA | mixinbooter               | 7.1                   | minecraft.jar                                 | None                                     |
       | LCHIJA | botania_tweaks_core       | -100                  | minecraft.jar                                 | None                                     |
       | LCHIJA | smoothfont                | mc1.12.2-2.1.4        | SmoothFont-mc1.12.2-2.1.4.jar                 | None                                     |
       | LCHIJA | baubles                   | 1.5.2                 | Baubles-1.12-1.5.2.jar                        | None                                     |
       | LCHIJA | thaumcraft                | 6.1.BETA26            | Thaumcraft-1.12.2-6.1.BETA26-patched.jar      | None                                     |
       | LCHIJA | thaumicaugmentation       | 1.12.2-2.1.12         | ThaumicAugmentation-1.12.2-2.1.12.jar         | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHIJA | advanced_alchemy_furnace  | 0.2.2                 | AdvancedAlchemyFurnace-0.2.2.jar              | None                                     |
       | LCHIJA | ctm                       | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                     | None                                     |
       | LCHIJA | appliedenergistics2       | rv6-stable-7          | appliedenergistics2-rv6-stable-7.jar          | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | gbook_snapshot            | 2.9.1.s5              | Guidebook-1.12.2-2.9.1.s5.jar                 | None                                     |
       | LCHIJA | arcanearchives            | 0.2.0.25-mixins8      | arcanearchives-0.2.0.25-mixins8.jar           | None                                     |
       | LCHIJA | guideapi                  | 1.12-2.1.8-63         | Guide-API-1.12-2.1.8-63.jar                   | None                                     |
       | LCHIJA | bloodmagic                | 1.12.2-2.4.3-105      | BloodMagic-1.12.2-2.4.3-105.jar               | None                                     |
       | LCHIJA | crafttweaker              | 4.1.20                | CraftTweaker2-1.12-4.1.20.698.jar             | None                                     |
       | LCHIJA | mtlib                     | 3.0.7                 | MTLib-3.0.7.jar                               | None                                     |
       | LCHIJA | modtweaker                | 4.0.19                | modtweaker-4.0.20.11.jar                      | None                                     |
       | LCHIJA | jei                       | 4.16.1.301            | jei_1.12.2-4.16.1.301.jar                     | None                                     |
       | LCHIJA | botania_tweaks            | 1.9.1                 | botaniatweaks-1.9.1.jar                       | None                                     |
       | LCHIJA | botania                   | r1.10-364             | Botania r1.10-364.4.jar                       | None                                     |
       | LCHIJA | codechickenlib            | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | avaritia                  | 3.4.0                 | Avaritia-1.12.2-kedition-universal.jar        | None                                     |
       | LCHIJA | base                      | 3.14.0                | base-1.12.2-3.14.0.jar                        | None                                     |
       | LCHIJA | betterquesting            | 4.1.0                 | BetterQuestingUnofficial-4.1.0.jar            | None                                     |
       | LCHIJA | bibliocraft               | 2.4.6                 | BiblioCraft[v2.4.6][MC1.12.2].jar             | None                                     |
       | LCHIJA | blockcraftery             | 1.12.2-1.3.1          | blockcraftery-1.12.2-1.3.1.jar                | None                                     |
       | LCHIJA | chameleon                 | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                      | None                                     |
       | LCHIJA | chisel                    | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
       | LCHIJA | containerfix              | 1.0                   | ContainerFix MC1.12.2 v1.0.jar                | None                                     |
       | LCHIJA | ctgui                     | 1.0.0                 | CraftTweaker2-1.12-4.1.20.698.jar             | None                                     |
       | LCHIJA | crafttweakerjei           | 2.0.3                 | CraftTweaker2-1.12-4.1.20.698.jar             | None                                     |
       | LCHIJA | custommainmenu            | 2.0.9.1               | CustomMainMenu-MC1.12.2-2.0.9.1.jar           | None                                     |
       | LCHIJA | dupefixproject            | 3.1.6                 | DupeFixProject-1.12.2-3.1.6.jar               | None                                     |
       | LCHIJA | familiarfauna             | 1.0.11                | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
       | LCHIJA | ftblib                    | 5.4.7.2               | FTBLib-5.4.7.2.jar                            | None                                     |
       | LCHIJA | ftbutilities              | 5.4.1.131             | FTBUtilities-5.4.1.131.jar                    | None                                     |
       | LCHIJA | gravestone                | 1.10.3                | gravestone-1.10.3.jar                         | None                                     |
       | LCHIJA | hammercore                | 2.0.6.32              | HammerLib-1.12.2-2.0.6.32.jar                 | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | waila                     | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
       | LCHIJA | igi|bloodmagicintegration | 1.2                   | IGI-BloodMagic-1.2.jar                        | None                                     |
       | LCHIJA | igi|thaumcraft            | 1.0a                  | IGI-Thaumcraft-1.0a.jar                       | None                                     |
       | LCHIJA | ikwid                     | 1.0.2                 | ikwid-1.0.2.jar                               | None                                     |
       | LCHIJA | lunatriuscore             | 1.2.0.42              | LunatriusCore-1.12.2-1.2.0.42-universal.jar   | None                                     |
       | LCHIJA | ingameinfoxml             | 2.8.2.94              | InGameInfoXML-1.12.2-2.8.2.94-universal.jar   | None                                     |
       | LCHIJA | inventorytweaks           | 1.64+dev.151.822d839  | InventoryTweaks-1.64+dev.151.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | isorropia                 | 0.1.13                | isorropia-kedtion.jar                         | None                                     |
       | LCHIJA | itlt                      | 1.0.4                 | itlt-1.12.x-1.0.4.jar                         | None                                     |
       | LCHIJA | lostmagic                 | 1.0                   | lostmagic-1.0.3.jar                           | None                                     |
       | LCHIJA | tbone                     | v1.6.8+mc1.12.2       | TBone-v1.6.8+mc1.12.2.jar                     | None                                     |
       | LCHIJA | metalchests               | v6.1.0+mc1.12.2       | MetalChests-v6.1.0+mc1.12.2.jar               | None                                     |
       | LCHIJA | testdummy                 | 1.12                  | MmmMmmMmmMmm-1.12-1.14.jar                    | None                                     |
       | LCHIJA | moreobservers             | 1.0                   | moreobserversmod-1.12.2-v1.0.0.jar            | None                                     |
       | LCHIJA | mousetweaks               | 3.1.4                 | mousetweaks-1.12.2-3.1.4.jar                  | None                                     |
       | LCHIJA | nanhealthfixer            | 1.12.2-0.0.1          | nanhealthfixer-1.12.2-0.0.1.jar               | None                                     |
       | LCHIJA | packagedauto              | 1.12.2-1.0.10.38      | PackagedAuto-1.12.2-1.0.10.38.jar             | None                                     |
       | LCHIJA | packagedthaumic           | 1.12.2-1.0.2.5        | PackagedThaumic-1.12.2-1.0.2.5.jar            | None                                     |
       | LCHIJA | patchouli                 | 1.0-23.6              | Patchouli-1.0-23.6.jar                        | None                                     |
       | LCHIJA | planarartifice            | 1.4.0-pre7            | planarartifice-1.4.0-pre7-patched.jar         | None                                     |
       | LCHIJA | forbiddenmagicre          | 0.6                   | ReForbidden Magic-1.12.2-v0.6.jar             | None                                     |
       | LCHIJA | resourceloader            | 1.5.3                 | ResourceLoader-MC1.12.1-1.5.3.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | riftfeed                  | 0.0.1                 | riftfeed-0.0.1.jar                            | None                                     |
       | LCHIJA | satako                    | 2.26                  | Satako 1.12-2.26.jar                          | None                                     |
       | LCHIJA | stackie                   | 1.6.0.48              | Stackie-1.12.2-1.6.0.48-universal.jar         | None                                     |
       | LCHIJA | storagedrawers            | 5.5.0                 | StorageDrawers-1.12.2-5.5.0.jar               | None                                     |
       | LCHIJA | traverse                  | 1.6.0                 | Traverse-1.12.2-1.6.0-69.jar                  | None                                     |
       | LCHIJA | storagedrawersunlimited   | 1.12.2-1.3.0          | StorageDrawersUnlimited-1.12.2-1.3.0.jar      | None                                     |
       | LCHIJA | surge                     | 2.0.79                | Surge-1.12.2-2.0.79.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | tcresearchpatcher         | 1.12.2-1.1.3          | ThaumcraftResearchPatcher-1.12.2-1.1.3.jar    | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHIJA | thaumic_calculator        | 0.4                   | Thaumic Calculations-1.12.2-0.4.jar           | None                                     |
       | LCHIJA | thaumadditions            | 12.7.8                | ThaumicAdditions-1.12.2-12.7.8.jar            | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | thaumicbases              | 3.5.200.1             | thaumicbases-3.5.230.0.jar                    | None                                     |
       | LCHIJA | thaumicbrewing            | 1.0.2                 | thaumicbrewing-1.0.2.jar                      | None                                     |
       | LCHIJA | thaumicjei                | 1.6.0                 | ThaumicJEI-1.12.2-1.6.0-27.jar                | None                                     |
       | LCHIJA | thaumicenergistics        | 2.2.6                 | thaumicenergistics-extended_life-2.2.7.jar    | None                                     |
       | LCHIJA | thaumicfixes              | 1.0                   | thaumicfixes-1.0-nolibs.jar                   | None                                     |
       | LCHIJA | tg                        | 0.3.1-kedition        | ThaumicGadgets-kedition-0.3.jar               | None                                     |
       | LCHIJA | tcinventoryscan           | 2.0.10                | ThaumicInventoryScanning_1.12.2-2.0.10.jar    | None                                     |
       | LCHIJA | thaumicperiphery          | 0.3.1                 | thaumicperiphery-0.3.1.jar                    | None                                     |
       | LCHIJA | thaumictinkerer           | 1.12.2-5.3-Unofficial | thaumictinkerer-1.12.2-5.3-Unofficial.jar     | None                                     |
       | LCHIJA | thaumicwonders            | 1.8.2                 | thaumicwonders-1.8.2.jar                      | None                                     |
       | LCHIJA | twilightforest            | 3.11.1021             | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
       | LCHIJA | unloader                  | 1.2.0                 | unloader-1.2.0.jar                            | None                                     |
       | LCHIJA | vanillafix                | 1.0.10-150            | VanillaFix-1.0.10-150.jar                     | None                                     |
       | LCHIJA | voidgoggles               | 0.1.0                 | voidgoggles-0.1.0.jar                         | None                                     |
       | LCHIJA | wailaharvestability       | 1.1.12                | WailaHarvestability-mc1.12-1.1.12.jar         | None                                     |
       | LCHIJA | wanionlib                 | 1.12.2-2.91           | WanionLib-1.12.2-2.91.jar                     | None                                     |
       | LCHIJA | warptheory                | 0.0.3.6               | WarpTheory1.12.2-0.0.3.7.jar                  | None                                     |
       | LCHIJA | xaerominimap              | 23.6.3                | Xaeros_Minimap_23.6.3_Forge_1.12.jar          | None                                     |
       | LCHIJA | xaeroworldmap             | 1.33.1                | XaerosWorldMap_1.33.1_Forge_1.12.jar          | None                                     |
       | LCHIJA | phosphor-lighting         | 1.12.2-0.2.6          | phosphor-1.12.2-0.2.6+build50-universal.jar   | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | mysticallib               | 1.12.2-1.13.0         | mysticallib-1.12.2-1.13.0.jar                 | None                                     |
       | LCHIJA | unidict                   | 1.12.2-3.0.10         | UniDict-1.12.2-3.0.10.jar                     | None                                     |
  Loaded coremods (and transformers): Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      MixinBooter (!mixinbooter-7.1.jar)
                                        
                                      Born in a Barn (Born In A Barn 1.8-1.12-1.2.jar)
                                        com.chocohead.biab.BornInABarn
                                      Thaumcraft Research Patcher Core Plugin (ThaumcraftResearchPatcher-1.12.2-1.1.3.jar)
                                        thecodex6824.tcresearchpatcher.Transformer
                                      Botania Tweaks Core (botaniatweaks-1.9.1.jar)
                                        quaternary.botaniatweaks.asm.BotaniaTweakerTransformer
                                      -Bansoukou- (_bansoukou-4.3.1.jar)
                                        
                                      AALoadingPlugin (arcanearchives-0.2.0.25-mixins8.jar)
                                        
                                      DupeFixProjectCoreMod (DupeFixProject-1.12.2-3.1.6.jar)
                                        
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.33.1_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.EntityPlayerMPTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                        xaero.map.core.transformer.SaveFormatTransformer
                                        xaero.map.core.transformer.BiomeColorHelperTransformer
                                        xaero.map.core.transformer.MinecraftServerTransformer
                                        xaero.map.core.transformer.MinecraftTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.4.jar)
                                        bre.smoothfont.asm.Transformer
                                      Planar Artifice Coremod (planarartifice-1.4.0-pre7-patched.jar)
                                        leppa.planarartifice.core.PATransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
                                        
                                      UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
                                        wanion.unidict.core.UniDictCoreModTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      HCASM (HammerLib-1.12.2-2.0.6.32.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.12.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      thaumicfixes (thaumicfixes-1.0-nolibs.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      TARCore (ThaumicAdditions-1.12.2-12.7.8.jar)
                                        
                                      XaeroMinimapPlugin (Xaeros_Minimap_23.6.3_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerMPTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.SaveFormatTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.MinecraftServerTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                        xaero.common.core.transformer.ModelRendererTransformer
  GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.5171' Renderer: 'Intel(R) HD Graphics 4400'
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  HammerCore Debug Information: Dependent Mods:
                                -Thaumic Additions: Reconstructed (thaumadditions) @ 12.7.8
  Patchouli open book context: n/a
  AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:ON
  Suspected Mods: Mouse Tweaks Unofficial (mousetweaks)
  Launched Version: ThaumicRenaissance - Kedition-6.0.1
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.5171, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Inlay Fix 1.0.zip, Modernity-format3-v3.9.1.zip, Sonomagy TC6 v1.6.zip, Thaum_pack.zip (incompatible), tmr0.26.zip (incompatible), PCL2 Skin.zip
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by xJon** [comment]
Would love to have this fixed.

**Comment by xJon** [comment]
@KELETU66666 Have you considered adding it to the internal blacklist, i.e. https://github.com/CleanroomMC/MouseTweaks/commit/1b015a1d2649f0f0be6f5ab992980d005fec7234?
